#+TITLE: guile-xcb
#+AUTHOR: Mark Witmer
#+DESCRIPTION: A Guile implementation of the X protocol using xml/xcb

* Overview

guile-xcb is a client-side implementation of the X protocol written
entirely in Guile. It makes use of the Guile compiler and virtual
machine to turn xml descriptions of the X protocol provided by the xcb
project into Guile object code files. These files can be loaded into a
process as conventional modules.

Support is included for the core X protocol as well as many of its
extensions.

* Samples and Documentation

Samples using guile-xcb can be found in the xcb/xml/samples
directory. They include:

- tinywm.scm: A guile-xcb implementation of tinywm
- win.scm: A simple demonstration of creating a window and receiving
  events
- randr.scm: Examine the physical displays the X server knows about
  and the virtual screens mapped to them

More detailed documentation resides in the texinfo manual included in
this distribution.

* Author

Mark Witmer is the author of this library. You can contact him at
[[mark@markwitmer.com]].

